spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luisgerardopinomendoza/devs4jcursomicroservicio
          default-label: main
          clone-on-start: true
server:
  port: 8889




